name: main
on:
  push:
    branches:
      - update

env:
  WOLFRAM_ID: ${{ secrets.WOLFRAM_ID }}
  WOLFRAM_PW: ${{ secrets.WOLFRAM_PW }}
  GITEE_KEY: ${{ secrets.GITEE_KEY }}

jobs:
  build:
    name: "init"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Wolfram Engine
      run: |
        wget https://account.wolfram.com/download/public/wolfram-engine/desktop/LINUX
        sudo bash LINUX -- -auto -verbose
        rm LINUX
    - name: Activate Wolfram Engine
      run: |
        /usr/bin/wolframscript -authenticate $WOLFRAM_ID $WOLFRAM_PW
        /usr/bin/wolframscript -activate
    - name: Install Paclets
      run: |
        /usr/bin/wolframscript -code 'PacletInstall["PacletSiteManager", "Site" -> "https://github.com/rnotlnglgq/WolframPacletSiteManager/raw/master"]'
    - name: Set SSH Key
      run: |
        mkdir ~/.ssh/
        unzip -P $GITEE_KEY -d ~/.ssh/ id.zip
        chmod 700 ~/.ssh/rnotlnglgq_auto
        echo $'StrictHostKeyChecking no\n UserKnownHostsFile /dev/null\n Host wlgiteeauto\nHostName gitee.com\n User rnotlnglgq\n IdentityFile ~/.ssh/rnotlnglgq_auto' > ~/.ssh/config
    - name: Git Clone 2
      run: |
        git clone git@wlgiteeauto:rnotlnglgq/WolframPacletMirror2.git
      continue-on-error: true
    - name: Update Paclets 2
      run: |
        cd WolframPacletMirror2
        /usr/bin/wolframscript -file '../run.wls'
      continue-on-error: true
    - name: Git Push 2
      run: |
        cd WolframPacletMirror2
        git remote add gitee git@wlgiteeauto:rnotlnglgq/WolframPacletMirror2.git
        git config --local user.name rnotlnglgq_auto
        git config --local user.email rnotlnglgq@outlook.com
        git config --local gc.auto 0
        git config --local http.postBuffer 524288000
        git add -A
        git commit -m "auto"
        du -sh .git
        git push gitee master
      continue-on-error: true