name: main
on:
  push:
    branches:
      - update

env:
  WOLFRAM_ID: ${{ secrets.WOLFRAM_ID }}
  WOLFRAM_PW: ${{ secrets.WOLFRAM_PW }}
  GITEE_KEY: ${{ secrets.GITEE_KEY }}

jobs:
  build:
    name: "init"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set SSH Key
      run: |
        mkdir ~/.ssh/
        cp ./config ~/.ssh/
        unzip -P $GITEE_KEY -d ~/.ssh/ id2.zip
        chmod 700 ~/.ssh/rnotlnglgq_auto2
    - name: Install Wolfram Engine
      run: |
        wget https://account.wolfram.com/download/public/wolfram-engine/desktop/LINUX
        sudo bash LINUX -- -auto -verbose
        rm LINUX
    - name: Activate Wolfram Engine
      run: |
        /usr/bin/wolframscript -authenticate $WOLFRAM_ID $WOLFRAM_PW
        /usr/bin/wolframscript -activate
    - name: Update Paclets Auto
      run: |
        ls -lh
        mkdir WolframPacletMirrorAuto
        cd WolframPacletMirrorAuto
        mkdir Paclets
        cp ../Requirement.wl ./
        /usr/bin/wolframscript -file '../run.wls'
    - name: Git Push Auto
      run: |
        cd WolframPacletMirrorAuto
        export GIT_TRACE_PACKET=1
        export GIT_TRACE=1
        export GIT_CURL_VERBOSE=1
        git init
        git remote add wlcoding wlcoding:rnotlnglgq/wpm/WolframPacletAuto.git
        git config --local user.name rnotlnglgq_auto
        git config --local user.email rnotlnglgq@outlook.com
        git config --local gc.auto 0
        git config --local http.postBuffer 524288000
        git add -A
        git commit -m "auto"
        du -sh .git
        git push wlcoding master -f
