name: main
on:
  push:
    branches:
      - update

env:
  WOLFRAM_ID: ${{ secrets.WOLFRAM_ID }}
  WOLFRAM_PW: ${{ secrets.WOLFRAM_PW }}
  GITEE_KEY: ${{ secrets.GITEE_KEY }}

jobs:
  build:
    name: "init"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Wolfram Engine
      run: |
        wget https://account.wolfram.com/download/public/wolfram-engine/desktop/LINUX
        sudo bash LINUX -- -auto -verbose
        rm LINUX
    - name: Activate Wolfram Engine
      run: |
        /usr/bin/wolframscript -authenticate $WOLFRAM_ID $WOLFRAM_PW
        /usr/bin/wolframscript -activate
    - name: Install Paclets
      run: |
        /usr/bin/wolframscript -code 'PacletInstall["PacletSiteManager", "Site" -> "https://github.com/rnotlnglgq/WolframPacletSiteManager/raw/master"]'
    - name: Set SSH Key
      run: |
        mkdir ~/.ssh/
        unzip -P $GITEE_KEY -d ~/.ssh/ id.zip
        chmod 700 ~/.ssh/rnotlnglgq_auto
        echo $'StrictHostKeyChecking no\n UserKnownHostsFile /dev/null\n Host wlgiteeauto\nHostName gitee.com\n User rnotlnglgq\n IdentityFile ~/.ssh/rnotlnglgq_auto' > ~/.ssh/config
    - name: Git Clone 3
      run: |
        git clone git@wlgiteeauto:rnotlnglgq/WolframPacletMirror3.git
      continue-on-error: true
    - name: Update Paclets 3
      run: |
        cd WolframPacletMirror3
        /usr/bin/wolframscript -file '../run.wls'
      continue-on-error: true
    - name: Git Push 3
      run: |
        cd WolframPacletMirror3
        rm -rf .git
        git init
        git remote add origin git@wlgiteeauto:rnotlnglgq/WolframPacletMirror3.git
        git config --local user.name rnotlnglgq_auto
        git config --local user.email rnotlnglgq@outlook.com
        git config --local gc.auto 0
        git config --local http.postBuffer 524288000
        git add -A
        git commit -m "auto"
        du -sh .git
        git push -f origin master
      continue-on-error: true
    - name: Git Clone 4
      run: |
        git clone git@wlgiteeauto:rnotlnglgq/WolframPacletMirror4.git
      continue-on-error: true
    - name: Update Paclets 4
      run: |
        cd WolframPacletMirror4
        /usr/bin/wolframscript -file '../run.wls'
      continue-on-error: true
    - name: Git Push 4
      run: |
        cd WolframPacletMirror4
        rm -rf .git
        git init
        git remote add origin git@wlgiteeauto:rnotlnglgq/WolframPacletMirror4.git
        git config --local user.name rnotlnglgq_auto
        git config --local user.email rnotlnglgq@outlook.com
        git config --local gc.auto 0
        git config --local http.postBuffer 524288000
        git add -A
        git commit -m "auto"
        du -sh .git
        git push -f origin master
      continue-on-error: true
    - name: Git Clone 5
      run: |
        git clone git@wlgiteeauto:rnotlnglgq/WolframPacletMirror5.git
      continue-on-error: true
    - name: Update Paclets 5
      run: |
        cd WolframPacletMirror5
        /usr/bin/wolframscript -file '../run.wls'
      continue-on-error: true
    - name: Git Push 5
      run: |
        cd WolframPacletMirror5
        rm -rf .git
        git init
        git remote add origin git@wlgiteeauto:rnotlnglgq/WolframPacletMirror5.git
        git config --local user.name rnotlnglgq_auto
        git config --local user.email rnotlnglgq@outlook.com
        git config --local gc.auto 0
        git config --local http.postBuffer 524288000
        git add -A
        git commit -m "auto"
        du -sh .git
        git push -f origin master
      continue-on-error: true
    - name: Git Clone 6
      run: |
        git clone git@wlgiteeauto:rnotlnglgq/WolframPacletMirror6.git
      continue-on-error: true
    - name: Update Paclets 6
      run: |
        cd WolframPacletMirror6
        /usr/bin/wolframscript -file '../run.wls'
      continue-on-error: true
    - name: Git Push 6
      run: |
        cd WolframPacletMirror6
        rm -rf .git
        git init
        git remote add origin git@wlgiteeauto:rnotlnglgq/WolframPacletMirror6.git
        git config --local user.name rnotlnglgq_auto
        git config --local user.email rnotlnglgq@outlook.com
        git config --local gc.auto 0
        git config --local http.postBuffer 524288000
        git add -A
        git commit -m "auto"
        du -sh .git
        git push -f origin master
      continue-on-error: true
    - name: Git Clone 7
      run: |
        git clone git@wlgiteeauto:rnotlnglgq/WolframPacletMirror7.git
      continue-on-error: true
    - name: Update Paclets 7
      run: |
        cd WolframPacletMirror7
        /usr/bin/wolframscript -file '../run.wls'
      continue-on-error: true
    - name: Git Push 7
      run: |
        cd WolframPacletMirror7
        rm -rf .git
        git init
        git remote add origin git@wlgiteeauto:rnotlnglgq/WolframPacletMirror7.git
        git config --local user.name rnotlnglgq_auto
        git config --local user.email rnotlnglgq@outlook.com
        git config --local gc.auto 0
        git config --local http.postBuffer 524288000
        git add -A
        git commit -m "auto"
        du -sh .git
        git push -f origin master
      continue-on-error: true
    - name: Git Clone 8
      run: |
        git clone git@wlgiteeauto:rnotlnglgq/WolframPacletMirror8.git
      continue-on-error: true
    - name: Update Paclets 8
      run: |
        cd WolframPacletMirror8
        /usr/bin/wolframscript -file '../run.wls'
      continue-on-error: true
    - name: Git Push 8
      run: |
        cd WolframPacletMirror8
        rm -rf .git
        git init
        git remote add origin git@wlgiteeauto:rnotlnglgq/WolframPacletMirror8.git
        git config --local user.name rnotlnglgq_auto
        git config --local user.email rnotlnglgq@outlook.com
        git config --local gc.auto 0
        git config --local http.postBuffer 524288000
        git add -A
        git commit -m "auto"
        du -sh .git
        git push -f origin master
      continue-on-error: true