name: main
on:
  push:
    branches:
      - update

env:
  WOLFRAM_ID: ${{ secrets.WOLFRAM_ID }}
  WOLFRAM_PW: ${{ secrets.WOLFRAM_PW }}
  GITEE_KEY: ${{ secrets.GITEE_KEY }}

jobs:
  build:
    name: "init"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set SSH Key
      run: |
        mkdir ~/.ssh/
        cp env/config ~/.ssh/
        unzip -P $GITEE_KEY -d ~/.ssh/ env/id2.zip
        chmod 700 ~/.ssh/rnotlnglgq_auto2
    - name: Install Wolfram Engine
      run: |
        wget https://account.wolfram.com/download/public/wolfram-engine/desktop/LINUX
        sudo bash LINUX -- -auto -verbose
        rm LINUX
    - name: Activate Wolfram Engine
      run: |
        /usr/bin/wolframscript -authenticate $WOLFRAM_ID $WOLFRAM_PW
        /usr/bin/wolframscript -activate
    - name: Update Paclets Auto
      run: |
        ls -lh
        git clone wlcoding:rnotlnglgq/wpm/WolframPacletAuto.git
        cd WolframPacletAuto
        cp ../env/.gitconfig ./
        cp ../env/.gitattributes ./
        cp ../Requirement.wl ./
        /usr/bin/wolframscript -file '../run.wls'
        ls -lh Paclets
    - name: Git Push Auto
      run: |
        cd WolframPacletAuto
        ssh -vT wlcoding
        git lfs track Paclets/*.paclet
        git lfs track PacletSite.m
        git lfs track PacletSite.mz
        git add -A
        git commit -m "auto"
        du -sh .git
        git push wlcoding master
