name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

env:
  WOLFRAM_ID: ${{ secrets.WOLFRAM_ID }}
  WOLFRAM_PW: ${{ secrets.WOLFRAM_PW }}
  GITEE_KEY: ${{ secrets.GITEE_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "test git"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Wolfram Engine
      run: |
        wget https://account.wolfram.com/download/public/wolfram-engine/desktop/LINUX
        sudo bash LINUX -- -auto -verbose
        rm LINUX
    - name: Activate Wolfram Engine
      run: |
        /usr/bin/wolframscript -authenticate $WOLFRAM_ID $WOLFRAM_PW
        /usr/bin/wolframscript -activate
    - name: Install Paclets
      run: |
        /usr/bin/wolframscript -code 'PacletInstall["CURLLink"];PacletInstall["latest/PacletMirrorManager.paclet"]'
    - name: Set SSH Key
      run: |
        mkdir ~/.ssh/
        unzip -P $GITEE_KEY -d ~/.ssh/ id.zip
        chmod 700 ~/.ssh/rnotlnglgq_auto
        echo $'StrictHostKeyChecking no\n UserKnownHostsFile /dev/null\n Host wlgiteeauto\nHostName gitee.com\n User rnotlnglgq\n IdentityFile ~/.ssh/rnotlnglgq_auto' > ~/.ssh/config
    - name: Git Clone
      run: |
        git clone git@wlgiteeauto:rnotlnglgq/WolframPacletGeneral.git
    - name: Update Paclets
      run: |
        cd WolframPacletGeneral
        /usr/bin/wolframscript -code 'NewestPaclet["SiteInfo" -> NewestSiteInfo[]] //PickNewestPaclet //UpdatePaclet;Print@BuildSiteInfo[]'
    - name: Git Push
      run: |
        cd WolframPacletGeneral
        git config --local user.name rnotlnglgq_auto
        git config --local user.email rnotlnglgq@outlook.com
        git add -A
        git commit -m "auto"
        git push origin master
